<?php
const servername = "localhost";
const username = "root";
const password = "root";
const dbname = "mydb";

function connectDb()
{
    static $connect = null;
    if (null === $connect) {
        $connect = mysqli_connect(servername, username, password, dbname) or die('Connection Error');
    }
    mysqli_query($connect, "
    -- MySQL Script generated by MySQL Workbench
    -- Mon Jul  5 20:31:44 2021
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering
    
    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    
    -- -----------------------------------------------------
    -- Schema mydb
    -- -----------------------------------------------------
    
    -- -----------------------------------------------------
    -- Schema mydb
    -- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
    USE `mydb` ;
    
    -- -----------------------------------------------------
    -- Table `mydb`.`users`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `mydb`.`users` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `full_name` VARCHAR(255) NOT NULL,
      `flag_active` BIT(1) NOT NULL,
      `email` VARCHAR(245) NOT NULL,
      `password` VARCHAR(60) NOT NULL,
      `flag_consent` BIT(1) NOT NULL,
      `phone` VARCHAR(45) NOT NULL,
      PRIMARY KEY (`id`))
    ENGINE = InnoDB;
    
    
    -- -----------------------------------------------------
    -- Table `mydb`.`groups`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `name` VARCHAR(145) NOT NULL,
      `description` VARCHAR(145) NOT NULL,
      PRIMARY KEY (`id`))
    ENGINE = InnoDB;
    
    
    -- -----------------------------------------------------
    -- Table `mydb`.`users_has_groups`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `mydb`.`users_has_groups` (
      `user_id` INT NOT NULL,
      `group_id` INT NOT NULL,
      `id` INT NOT NULL AUTO_INCREMENT,
      PRIMARY KEY (`id`, `group_id`, `user_id`),
      INDEX `fk_users_has_groups_groups1_idx` (`group_id` ASC) VISIBLE,
      INDEX `fk_users_has_groups_users_idx` (`user_id` ASC) VISIBLE,
      CONSTRAINT `fk_users_has_groups_users`
        FOREIGN KEY (`user_id`)
        REFERENCES `mydb`.`users` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
      CONSTRAINT `fk_users_has_groups_groups1`
        FOREIGN KEY (`group_id`)
        REFERENCES `mydb`.`groups` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;
    
    
    -- -----------------------------------------------------
    -- Table `mydb`.`colors`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `mydb`.`colors` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `hex` VARCHAR(45) NOT NULL,
      `description` VARCHAR(45) NOT NULL,
      PRIMARY KEY (`id`))
    ENGINE = InnoDB;
    
    
    -- -----------------------------------------------------
    -- Table `mydb`.`sections`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `mydb`.`sections` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `name` VARCHAR(145) NOT NULL,
      `color` VARCHAR(45) NOT NULL,
      `date_create` DATETIME NOT NULL,
      `user_id` INT NOT NULL,
      `colors_id` INT NOT NULL,
      `parent_id` INT NOT NULL,
      PRIMARY KEY (`id`),
      INDEX `fk_messages_groups_users1_idx` (`user_id` ASC) VISIBLE,
      INDEX `fk_messages_groups_colors1_idx` (`colors_id` ASC) VISIBLE,
      CONSTRAINT `fk_messages_groups_users1`
        FOREIGN KEY (`user_id`)
        REFERENCES `mydb`.`users` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
      CONSTRAINT `fk_messages_groups_colors1`
        FOREIGN KEY (`colors_id`)
        REFERENCES `mydb`.`colors` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;
    
    
    -- -----------------------------------------------------
    -- Table `mydb`.`messages`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `text` TEXT NOT NULL,
      `title` TEXT NOT NULL,
      `date_create` DATETIME NOT NULL,
      `subgroup_id` INT NULL,
      `user_recipient` INT NOT NULL,
      `user_creator_id` INT NOT NULL,
      PRIMARY KEY (`id`),
      INDEX `fk_messages_users1_idx` (`user_creator_id` ASC) VISIBLE,
      CONSTRAINT `fk_messages_users1`
        FOREIGN KEY (`user_creator_id`)
        REFERENCES `mydb`.`users` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;
    
    
    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

    ");
    return $connect;
}

function getUsersInfo()
{
    $connect = connectDb();
    $result = mysqli_query($connect, "select * from users");
    mysqli_close($connect);
    return $result;
}

function getUserByLogin($login, $password)
{
    $connect = connectDb();
    $login = mysqli_real_escape_string($connect, $login);
    $result = mysqli_query($connect, "select * from users u where u.login = '$login' limit 1");
    $passwordBD = '';
    $user = [];
    while($row = mysqli_fetch_assoc($result)) {
        $user = $row;
        $passwordBD = $row['password'];
    }
    mysqli_close($connect);
    if (password_verify($password, $passwordBD)) {
        return $user;
    }
}

function getGroups($userId)
{
    $connect = connectDb();
    $userId = mysqli_real_escape_string($connect, $userId);
    $result = mysqli_query($connect, "
        select distinct uhg.group_id, g.name from users u
        inner join users_has_groups uhg on $userId = uhg.user_id
        inner join `groups` g on uhg.group_id = g.id
");
    mysqli_close($connect);
    return $result;
}